version: "3.8"
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: neko
      POSTGRES_PASSWORD: neko123
      POSTGRES_DB: nekodb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:

# postgres://neko:neko123@localhost:5432/nekodb?sslmode=disable